[
  # Have single bins that really aren't a sensible mainProgram
  [ "perlPackages" "AlienSDL" ]
  [ "perlPackages" "DevelCheckOS" ]
  [ "perlPackages" "DevelChecklib" ]
  [ "perlPackages" "GlibObjectIntrospection" ]
  [ "perlPackages" "libapreq2" ]

  # Have multiple bins, none of which should obviously be blessed as mainProgram
  [ "nodePackages" "code-theme-converter" ]
  [ "nodePackages" "hs-client" ]
  [ "nodePackages" "ijavascript" ]
  [ "nodePackages" "manta" ]
  [ "nodePackages" "nijs" ]
  [ "nodePackages" "smartdc" ]
  [ "nodePackages" "vega-cli" ]
  [ "nodePackages" "vega-lite" ]
  [ "nodePackages" "vscode-langservers-extracted" ]

  [ "ocamlPackages" "awa" ]
  [ "ocamlPackages" "cohttp-async" ]
  [ "ocamlPackages" "cohttp-lwt-unix" ]
  [ "ocamlPackages" "core" ]
  [ "ocamlPackages" "cudf" ]
  [ "ocamlPackages" "eliom" ]
  [ "ocamlPackages" "kafka_lwt" ]
  [ "ocamlPackages" "lablgtk3" ]
  [ "ocamlPackages" "ocamlnet" ]
  [ "ocamlPackages" "pyml" ]
  [ "ocamlPackages" "reason" ]

  [ "perlPackages" "Clipboard" ]
  [ "perlPackages" "ConvertUU" ]
  [ "perlPackages" "DBI" ]
  [ "perlPackages" "DateManip" ]
  [ "perlPackages" "Deliantra" ]
  [ "perlPackages" "DevelNYTProf" ]
  [ "perlPackages" "FileMimeInfo" ]
  [ "perlPackages" "GooCanvas" ]
  [ "perlPackages" "HTMLFormFu" ]
  [ "perlPackages" "HTMLMason" ]
  [ "perlPackages" "LWP" ]
  [ "perlPackages" "LWPUserAgent" ]
  [ "perlPackages" "MP3Tag" ]
  [ "perlPackages" "MathPrimeUtil" ]
  [ "perlPackages" "MaxMindDBReader" ]
  [ "perlPackages" "ModuleCPANfile" ]
  [ "perlPackages" "NetIP" ]
  [ "perlPackages" "OpenOfficeOODoc" ]
  [ "perlPackages" "PerconaToolkit" ]
  [ "perlPackages" "Razor2ClientAgent" ]
  [ "perlPackages" "SOAPLite" ]
  [ "perlPackages" "TAPParserSourceHandlerpgTAP" ]
  [ "perlPackages" "TemplateToolkit" ]
  [ "perlPackages" "TextBibTeX" ]
  [ "perlPackages" "TextNSP" ]
  [ "perlPackages" "TextPDF" ]
  [ "perlPackages" "TextRecordParser" ]
  [ "perlPackages" "Tk" ]
  [ "perlPackages" "VMEC2" ]
  [ "perlPackages" "XMLEncoding" ]
  [ "perlPackages" "XMLRules" ]
  [ "perlPackages" "YAMLPP" ]
  [ "perlPackages" "cam_pdf" ]
  [ "perlPackages" "maatkit" ]
  [ "perlPackages" "podlators" ]

  # Added automatically
  ]
